#ifndef RICH_FFI_H
#define RICH_FFI_H

/* Generated by cbindgen from rich-ffi. DO NOT EDIT BY HAND. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque console handle. C/C++ only ever sees a `RichConsole*`.
//
// Backed by a capture console: rendering writes ANSI (or plain) text to an
// in-memory buffer that `rich_console_render_markup` hands back as an owned
// string. The caller decides where it goes (stdout, a log line, etc.).
typedef struct RichConsole RichConsole;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Create a new console. Returns NULL on allocation/init failure.
//
// Defaults: markup + emoji enabled, truecolor, and `force_terminal = true` so
// ANSI is emitted into the captured string. A consumer that may be piped should
// immediately call `rich_console_set_force_terminal` with its `isatty` result.
RichConsole *rich_console_new(void);

// Free a console created by `rich_console_new`. NULL is a no-op.
void rich_console_free(RichConsole *console);

// Force (or unforce) terminal/ANSI output.
//
// Pass the result of `isatty()` here: `true` emits ANSI styling, `false` emits
// plain text. This is the switch for SafeTunnel's daemon — styled under
// `--foreground` on a TTY, plain when writing to journald/syslog.
void rich_console_set_force_terminal(RichConsole *console, bool force);

// Set the render width and height in cells (controls wrapping).
void rich_console_set_size(RichConsole *console, unsigned int width, unsigned int height);

// Set the color system: 0 = none/monochrome, 1 = standard (16),
// 2 = 8-bit (256), 3 = truecolor (24-bit), 4 = Windows legacy.
// Out-of-range values are ignored.
void rich_console_set_color_system(RichConsole *console, int system);

// Enable or disable BBCode-style markup parsing (e.g. `[bold]...[/]`).
void rich_console_set_markup_enabled(RichConsole *console, bool enabled);

// Enable or disable `:emoji_name:` substitution.
void rich_console_set_emoji_enabled(RichConsole *console, bool enabled);

// Current render width in cells. Returns 0 if `console` is NULL.
unsigned int rich_console_width(RichConsole *console);

// Render a markup string to an owned, NUL-terminated C string.
//
// Honors the console's current markup/emoji/color/width settings. No trailing
// newline is appended — the caller controls line endings. Returns NULL if
// `console`/`markup` is NULL, `markup` is not valid UTF-8, or rendering fails.
//
// The returned pointer MUST be freed with `rich_string_free`.
char *rich_console_render_markup(RichConsole *console, const char *markup);

// Free a string returned by `rich_console_render_markup`. NULL is a no-op.
void rich_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RICH_FFI_H */
