#ifndef RICH_FFI_H
#define RICH_FFI_H

/* Generated by cbindgen from rich-ffi. DO NOT EDIT BY HAND. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Opaque console handle. C/C++ only ever sees a `RichConsole*`.
//
// Backed by a capture console: rendering writes ANSI (or plain) text to an
// in-memory buffer that `rich_console_render_markup` hands back as an owned
// string. The caller decides where it goes (stdout, a log line, etc.).
typedef struct RichConsole RichConsole;

// Opaque, type-erased renderable — the universal composition currency.
//
// Anything that can be rendered or nested inside a container (Panel, Table,
// Tree, Align, ...) is moved through one of these. A `RichRenderable*` is
// produced by a typed builder's `*_finish` function (e.g. `rich_text_finish`)
// and either rendered with `rich_console_render`, passed into a consuming
// container constructor, or freed with `rich_renderable_free`.
typedef struct RichRenderable RichRenderable;

// Opaque parsed-style handle wrapping a `rich_rs::Style`. Created by
// `rich_style_parse`, freed by `rich_style_free`. Held opaque for
// forward-compat even though `Style` is `Copy` underneath.
typedef struct RichStyle RichStyle;

// Opaque `Text` builder handle. Build it, optionally style it, then either
// `rich_text_finish` it into a `RichRenderable` or `rich_text_free` it.
//
// The inner `Option<Text>` lets `rich_text_finish` take the value by move.
typedef struct RichText RichText;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Create a new console. Returns NULL on allocation/init failure.
//
// Defaults: markup + emoji enabled, truecolor, and `force_terminal = true` so
// ANSI is emitted into the captured string. A consumer that may be piped should
// immediately call `rich_console_set_force_terminal` with its `isatty` result.
RichConsole *rich_console_new(void);

// Free a console created by `rich_console_new`. NULL is a no-op.
void rich_console_free(RichConsole *console);

// Force (or unforce) terminal/ANSI output.
//
// Pass the result of `isatty()` here: `true` emits ANSI styling, `false` emits
// plain text. This is the switch for SafeTunnel's daemon — styled under
// `--foreground` on a TTY, plain when writing to journald/syslog.
void rich_console_set_force_terminal(RichConsole *console, bool force);

// Set the render width and height in cells (controls wrapping).
void rich_console_set_size(RichConsole *console, unsigned int width, unsigned int height);

// Set the color system: 0 = none/monochrome, 1 = standard (16),
// 2 = 8-bit (256), 3 = truecolor (24-bit), 4 = Windows legacy.
// Out-of-range values are ignored.
void rich_console_set_color_system(RichConsole *console, int system);

// Enable or disable BBCode-style markup parsing (e.g. `[bold]...[/]`).
void rich_console_set_markup_enabled(RichConsole *console, bool enabled);

// Enable or disable `:emoji_name:` substitution.
void rich_console_set_emoji_enabled(RichConsole *console, bool enabled);

// Current render width in cells. Returns 0 if `console` is NULL.
unsigned int rich_console_width(RichConsole *console);

// Render a markup string to an owned, NUL-terminated C string.
//
// Honors the console's current markup/emoji/color/width settings. No trailing
// newline is appended — the caller controls line endings. Returns NULL if
// `console`/`markup` is NULL, `markup` is not valid UTF-8, or rendering fails.
//
// The returned pointer MUST be freed with `rich_string_free`.
char *rich_console_render_markup(RichConsole *console, const char *markup);

// Free a string returned by `rich_console_render_markup`. NULL is a no-op.
void rich_string_free(char *s);

// Render a `RichRenderable` to an owned, NUL-terminated C string.
//
// BORROWS `renderable`: the handle stays valid and the caller still owns it
// (free it later with `rich_renderable_free` unless it was consumed by a
// container). Honors the console's current force-terminal / color / width
// settings, so `set_force_terminal(false)` yields plain text with zero ANSI.
// No trailing newline is appended.
//
// Returns NULL if `console`/`renderable` is NULL or rendering fails. A
// non-NULL result MUST be freed with `rich_string_free`.
char *rich_console_render(RichConsole *console, const RichRenderable *renderable);

// Free a `RichRenderable` created by a `*_finish` function but never passed
// into a consuming container. NULL is a no-op.
void rich_renderable_free(RichRenderable *renderable);

// Create a `RichText` from plain text (no markup parsing).
//
// `text` must be valid NUL-terminated UTF-8. Returns NULL if `text` is NULL
// or not valid UTF-8. Free with `rich_text_finish` or `rich_text_free`.
RichText *rich_text_new(const char *text);

// Create a `RichText` by parsing console markup (e.g. `[bold red]hi[/]`).
//
// Honors the console's markup/emoji/highlight settings via `Console::render_str`.
// `markup` must be valid NUL-terminated UTF-8. Returns NULL if either pointer
// is NULL or `markup` is not valid UTF-8. Free with `rich_text_finish` or
// `rich_text_free`. The `console` handle is borrowed (not consumed).
RichText *rich_text_new_markup(RichConsole *console, const char *markup);

// Apply a base style (e.g. `"bold red on white"`) to a `RichText`.
//
// Parses `style` with `Style::parse` and sets it as the text's base style via
// `Text::set_base_style`. A NULL/invalid/unparseable `style` is a no-op (the
// text is left unchanged). Does not consume the handle.
void rich_text_set_style(RichText *text, const char *style);

// CONSUME a `RichText`, erasing it into the type-erased `RichRenderable`
// composition currency. The `RichText*` is invalid afterward.
//
// Returns NULL if `text` is NULL or was already finished. The returned
// `RichRenderable*` must be freed with `rich_renderable_free` (unless it is
// passed into a consuming container).
RichRenderable *rich_text_finish(RichText *text);

// Free a `RichText` that was created but never `rich_text_finish`ed.
// NULL is a no-op.
void rich_text_free(RichText *text);

// Parse a style string (e.g. `"bold red on white"`) into a `RichStyle`.
//
// `style` must be valid NUL-terminated UTF-8. Returns NULL if `style` is NULL,
// not valid UTF-8, or produces no actual style (empty/whitespace input, or
// input whose tokens are all unrecognized — e.g. `"nonsense-xyz"`). A non-NULL
// result MUST be freed with `rich_style_free`.
RichStyle *rich_style_parse(const char *style);

// Free a `RichStyle` created by `rich_style_parse`. NULL is a no-op.
void rich_style_free(RichStyle *style);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RICH_FFI_H */
