#!/usr/bin/env python3

"""
Generate `src/spinner_data.inc.rs` from the locally installed Python Rich spinner catalog.

This script is a developer tool (not required at runtime). The generated file is committed
so building rich-rs doesn't depend on Python being installed.

Usage:
  python3 tools/generate_spinner_data.py > src/spinner_data.inc.rs
"""

from __future__ import annotations

import rich._spinners as spinners  # type: ignore


def rust_str_literal(s: str) -> str:
    # Escape for a regular Rust string literal.
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    s = s.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    return f'"{s}"'


def main() -> None:
    items = sorted(spinners.SPINNERS.items(), key=lambda kv: kv[0])

    names = [name for name, _ in items]
    print("// This file is @generated by tools/generate_spinner_data.py")
    print("// Do not edit by hand.")
    print()

    print("#[allow(dead_code)]")
    print("pub(crate) fn spinner_names() -> &'static [&'static str] {")
    print("    &[")
    for name in names:
        print(f"        {rust_str_literal(name)},")
    print("    ]")
    print("}")
    print()

    print("pub(crate) fn get_spinner_def(name: &str) -> Option<SpinnerDef> {")
    print("    match name {")

    for name, value in items:
        interval = int(value["interval"])
        frames = value["frames"]
        if isinstance(frames, str):
            frames_list = list(frames)
        else:
            frames_list = list(frames)

        frames_rust = ", ".join(rust_str_literal(frame) for frame in frames_list)
        print(f"        {rust_str_literal(name)} => Some(SpinnerDef {{")
        print(f"            frames: &[{frames_rust}],")
        print(f"            interval_ms: {interval}u64,")
        print("        }),")

    print("        _ => None,")
    print("    }")
    print("}")


if __name__ == '__main__':
    main()
